import { Constants } from "./interface";
export const constant: Constants = {
  shopBazaar: "shopBazaar",
  customerDetails: "Customer Details",
  buyNow: "Buy Now",
  deliveryAddress: "Delivery Address",
  searchProductsHere: "search products here",
  noProductsFound: "No Products Found",
  cartEmpty: "Your Cart is Empty",
  addToCart: "Add To Cart",
  removeFromCart: "Remove From Cart",
  laptop: "Laptops",
  headphone: "Headphones",
  rupees: "₹",
  totalPrice: "Total Price",
  firstName: "First Name",
  lastName: "Last Name",
  email: "Email",
  gender: "Gender",
  mobileNumber: "Mobile",
  male: "MALE",
  female: "FEMALE",
  other: "OTHER",
  register: "Register",
  address: "Address",
  password: "Password",
  clickToLogin: "click to login",
  clickToRegister: "click to register",
  login: "Login",
  logout: "Logout",
  orderSummary: "Order summary"
};
